/**
 * Engineering disciplines
 * @module constants/disciplines
 */

export const DISCIPLINES = {
  PROCESS: 'PROCESS',
  MECHANICAL: 'MECHANICAL',
  ELECTRICAL: 'ELECTRICAL',
  CIVIL: 'CIVIL',
  INSTRUMENTATION: 'INSTRUMENTATION',
  PIPING: 'PIPING',
  STRUCTURAL: 'STRUCTURAL',
};

export const DISCIPLINE_LABELS = {
  [DISCIPLINES.PROCESS]: 'Procesos',
  [DISCIPLINES.MECHANICAL]: 'Mecánica',
  [DISCIPLINES.ELECTRICAL]: 'Eléctrica',
  [DISCIPLINES.CIVIL]: 'Civil',
  [DISCIPLINES.INSTRUMENTATION]: 'Instrumentación & Control',
  [DISCIPLINES.PIPING]: 'Tuberías',
  [DISCIPLINES.STRUCTURAL]: 'Estructural',
};

export const DISCIPLINE_COLORS = {
  [DISCIPLINES.PROCESS]: '#3b82f6',
  [DISCIPLINES.MECHANICAL]: '#8b5cf6',
  [DISCIPLINES.ELECTRICAL]: '#eab308',
  [DISCIPLINES.CIVIL]: '#6b7280',
  [DISCIPLINES.INSTRUMENTATION]: '#10b981',
  [DISCIPLINES.PIPING]: '#f59e0b',
  [DISCIPLINES.STRUCTURAL]: '#ef4444',
};

