/**
 * PETROECUADOR standardized codes for disciplines and types
 */

// Discipline select options with numeric discipline codes used in document code
export const PETRO_DISCIPLINE_OPTIONS = [
  { value: '00', label: 'Gestión General' },
  { value: '05', label: 'Listado Master Documentos' },
  { value: '01', label: 'Procesos' },
  { value: '10', label: 'Procesos (Planos/Diagramas)' },
  { value: '11', label: 'Proceso - Diagrama de Flujo' },
  { value: '12', label: 'Proceso - Balance de Masas' },
  { value: '20', label: 'Mecánico General' },
  { value: '21', label: 'Recipientes' },
  { value: '22', label: 'Tanques' },
  { value: '23', label: 'Intercambiador de Calor' },
  { value: '24', label: 'Calentadores' },
  { value: '25', label: 'Equipo Rotativo' },
  { value: '30', label: 'Civil General' },
  { value: '31', label: 'Topografía' },
  { value: '32', label: 'Cimentaciones' },
  { value: '33', label: 'Estructuras de Hormigón' },
  { value: '34', label: 'Estructuras de Acero' },
  { value: '35', label: 'Arquitectura' },
  { value: '36', label: 'Diseño Vial' },
  { value: '37', label: 'Instalaciones Sanitarias' },
  { value: '39', label: 'Sistema de Información Geográfica' },
  { value: '50', label: 'Tubería General' },
  { value: '53', label: 'Isométricos' },
  { value: '54', label: 'Detalle de Tubería' },
  { value: '55', label: 'Arreglo de Tubería' },
  { value: '56', label: 'Soportes' },
  { value: '58', label: 'Ruta de Oleoducto' },
  { value: '59', label: 'Detalle de Oleoducto' },
  { value: '60', label: 'Instrumentación General' },
  { value: '61', label: 'Matriz Causa y Efecto' },
  { value: '62', label: 'Ubicación de Instrumentos' },
  { value: '63', label: 'Diagramas de Lazo' },
  { value: '64', label: 'Cableado de Instrumentación' },
  { value: '65', label: 'Panel de Control' },
  { value: '66', label: 'Hook-up de Instrumentos' },
  { value: '67', label: 'Ruteo de Cables y Bandejas' },
  { value: '68', label: 'Diagrama de Bloque' },
  { value: '69', label: 'Diagramas Lógicos' },
  { value: '70', label: 'Eléctrico General' },
  { value: '71', label: 'Planta de Equipos Eléctricos' },
  { value: '72', label: 'Clasificación de Área' },
  { value: '73', label: 'Diagramas de Potencia' },
  { value: '74', label: 'Diagramas de Iluminación' },
  { value: '75', label: 'Diagramas de Cableado' },
  { value: '76', label: 'Conexiones a Tierra' },
  { value: '77', label: 'Detalle de Instalación Eléctrica' },
  { value: '78', label: 'Ruteo de Cable Eléctrico' },
  { value: '79', label: 'Diagramas Unifilares' },
  { value: '80', label: 'Comunicaciones General' },
  { value: '82', label: 'Ubicación de Dispositivos' },
  { value: '84', label: 'Diagrama de Conexionado' },
  { value: '85', label: 'Paneles / Racks' },
  { value: '86', label: 'Hook-up de Componentes' },
  { value: '87', label: 'Ruteo de Cables y Detalles' },
  { value: '88', label: 'Diagrama de Bloque / Arquitecturas' },
  { value: '90', label: 'Skid - Planos Generales' },
  { value: '95', label: 'Protección Catódica General' },
  { value: '96', label: 'Diag. Instalaciones Generales' },
  { value: '97', label: 'Diag. Instalaciones Detallados' },
];

// Mapping of main discipline code to its available type codes and labels
export const PETRO_DISCIPLINE_TO_TYPES = {
  '00': [ { code: '00', label: 'Gestión General' } ],
  '05': [ { code: '05', label: 'Listado Master Documentos' } ],
  '01': [
    { code: '01', label: 'P&ID / PFD' },
    { code: '11', label: 'Diagrama de Flujo de Proceso' },
    { code: '12', label: 'Balance de Masas' },
  ],
  '20': [
    { code: '20', label: 'Mecánico General' },
    { code: '21', label: 'Recipientes' },
    { code: '22', label: 'Tanques' },
    { code: '23', label: 'Intercambiador de Calor' },
    { code: '24', label: 'Calentadores' },
    { code: '25', label: 'Equipo Rotativo' },
  ],
  '30': [
    { code: '30', label: 'Civil General' },
    { code: '31', label: 'Topografía' },
    { code: '32', label: 'Cimentaciones' },
    { code: '33', label: 'Estructuras de Hormigón' },
    { code: '34', label: 'Estructuras de Acero' },
    { code: '35', label: 'Arquitectura' },
    { code: '36', label: 'Diseño Vial' },
    { code: '37', label: 'Instalaciones Sanitarias' },
    { code: '39', label: 'Sistema de Información Geográfica' },
  ],
  '50': [
    { code: '50', label: 'Tubería General' },
    { code: '53', label: 'Isométricos' },
    { code: '54', label: 'Detalle de Tubería' },
    { code: '55', label: 'Arreglo de Tubería' },
    { code: '56', label: 'Soportes' },
    { code: '58', label: 'Ruta de Oleoducto' },
    { code: '59', label: 'Detalle de Oleoducto' },
  ],
  '60': [
    { code: '60', label: 'Instrumentación General' },
    { code: '61', label: 'Matriz Causa y Efecto' },
    { code: '62', label: 'Ubicación de Instrumentos' },
    { code: '63', label: 'Diagramas de Lazo' },
    { code: '64', label: 'Cableado de Instrumentación' },
    { code: '65', label: 'Panel de Control' },
    { code: '66', label: 'Hook-up de Instrumentos' },
    { code: '67', label: 'Ruteo de Cables y Bandejas' },
    { code: '68', label: 'Diagrama de Bloque' },
    { code: '69', label: 'Diagramas Lógicos' },
  ],
  '70': [
    { code: '70', label: 'Eléctrico General' },
    { code: '71', label: 'Planta de Equipos Eléctricos' },
    { code: '72', label: 'Clasificación de Área' },
    { code: '73', label: 'Diagramas de Potencia' },
    { code: '74', label: 'Diagramas de Iluminación' },
    { code: '75', label: 'Diagramas de Cableado' },
    { code: '76', label: 'Conexiones a Tierra' },
    { code: '77', label: 'Detalle de Instalación Eléctrica' },
    { code: '78', label: 'Ruteo de Cable Eléctrico' },
    { code: '79', label: 'Diagramas Unifilares' },
  ],
  '80': [
    { code: '80', label: 'Comunicaciones General' },
    { code: '82', label: 'Ubicación de Dispositivos' },
    { code: '84', label: 'Diagrama de Conexionado' },
    { code: '85', label: 'Paneles / Racks' },
    { code: '86', label: 'Hook-up de Componentes' },
    { code: '87', label: 'Ruteo de Cables y Detalles' },
    { code: '88', label: 'Diagrama de Bloque / Arquitecturas' },
  ],
  '90': [ { code: '90', label: 'Skid - Planos Generales' } ],
  '95': [
    { code: '95', label: 'Protección Catódica General' },
    { code: '96', label: 'Diag. Instalaciones Generales' },
    { code: '97', label: 'Diag. Instalaciones Detallados' },
  ],
};


